# -*- coding: utf-8 -*-
"""Bjj-App_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuihtCrDHMyRUGR-sivL6md0-4Ypnr5Z
"""

#Import the Libraries
import os
import datetime as dt
import re
import html
import pandas as pd
import plotly.express as px
!pip install streamlit
import streamlit as st

def log_training():
    st.title('📝 Log Training')
    st.caption('Record a training session using the same fields as the original notebook.')

    with st.form('log'):
        a, b, c = st.columns(3)

        date = a.date_input('Date', dt.date.today())
        rank = b.selectbox(
            'Rank',
            ['White', 'Blue', 'Purple', 'Brown', 'Black'],
            index=1
        )
        stripes = c.slider('Stripes', 0, 4, 0)

        a, b, c = st.columns(3)

        style = a.selectbox('Style', ['Gi', 'No-Gi', 'Both'])
        duration = b.number_input(
            'Duration (hours)',
            min_value=0.1,
            value=1.0,
            step=0.1
        )
        rounds = c.number_input(
            'Rounds',
            min_value=0,
            value=5,
            step=1
        )

        tech = st.text_input(
            'Techniques Trained',
            placeholder='Triangle, Armbar'
        )

        a, b = st.columns(2)

        given = a.number_input(
            'Submissions Given',
            min_value=0,
            value=0
        )

        received = b.number_input(
            'Submissions Received',
            min_value=0,
            value=0
        )

        notes = st.text_area('Notes')

        if st.form_submit_button(
            'Save Training Session',
            type='primary'
        ):
            d = logs()

            row = {
                'Date': date.strftime('%Y-%m-%d'),
                'Rank': rank,
                'Stripes': stripes,
                'Style': style,
                'Duration': duration,
                'Rounds': rounds,
                'Techniques_trained': tech,
                'Submissions_Given': given,
                'Submissions_Received': received,
                'Notes': notes
            }

            pd.concat(
                [d, pd.DataFrame([row])],
                ignore_index=True
            ).to_csv(LOGFILE, index=False)

            st.success('Training session logged.')
            st.rerun()

    st.subheader('Training History')

    st.dataframe(
        logs().sort_values('Date', ascending=False),
        use_container_width=True,
        hide_index=True
    )